from pathlib import Path
p=Path('index.html');s=p.read_text(encoding='utf-8')
old="async function load(){try{[db,catalog]=await Promise.all([fetch('data/ranking.json?'+Date.now()).then(r=>r.json()),fetch('data/catalog.json?'+Date.now()).then(r=>r.json())]);$('#status').textContent='Atualizado '+new Date(db.updated_at).toLocaleString('pt-BR');$('#notice').innerHTML=db.message;$('#catalogCount').textContent=catalog.count;$('#quoteDate').textContent=new Date(db.quote_date+'T12:00').toLocaleDateString('pt-BR');renderCatalog();renderRank()}catch(e){$('#notice').innerHTML='<b>Falha ao carregar a base.</b> A última publicação válida foi preservada.';$('#status').textContent='Erro de carga'}"
new="async function load(){try{const stamp=Date.now();const rr=await fetch('data/ranking.json?'+stamp);if(!rr.ok)throw new Error('ranking '+rr.status);db=await rr.json();try{const cr=await fetch('data/catalog.json?'+stamp);if(!cr.ok)throw new Error('catalog '+cr.status);catalog=await cr.json()}catch(catalogError){catalog={updated_at:db.updated_at,count:db.items.length,items:db.items.map(x=>({ticker:x.ticker,name:x.name,price:x.price,pe:x.pe,pvp:x.pvp,dy:x.dy,roe:x.roe,roic:x.roic,margin:x.margin,growth:x.growth,debt_equity:x.debt_equity,ev_ebitda:x.ev_ebitda,liquidity_2m:x.liquidity_2m}))}}$('#status').textContent='Atualizado '+new Date(db.updated_at).toLocaleString('pt-BR');$('#notice').innerHTML=(catalog.count===db.items.length?'<b>Modo resiliente:</b> ranking disponível; catálogo amplo ainda sincronizando. ':'' )+db.message;$('#catalogCount').textContent=catalog.count;$('#quoteDate').textContent=new Date(db.quote_date+'T12:00').toLocaleDateString('pt-BR');renderCatalog();renderRank()}catch(e){$('#notice').innerHTML='<b>Não foi possível carregar nem a última base válida.</b>';$('#status').textContent='Erro de carga'}"
if old not in s:raise SystemExit('trecho load não localizado')
s=s.replace(old,new)
p.write_text(s,encoding='utf-8')
assert 'Modo resiliente' in s and 'Promise.all' not in s
print('fallback resiliente aplicado')
